name: help_evans_escape
description: In continuation of the story Evan Tries An O Level written by Colin Dexter .This project was created for my grade 12 English Project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  maze: ^2.0.1
  cupertino_icons: ^0.1.3
  introduction_screen: ^1.0.9
  shared_preferences: ^0.5.10
  splashscreen: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf
        
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-BoldItalic.ttf
